# Generated by Django 2.2.8 on 2021-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mark_best',
            field=models.BooleanField(default=False),
        ),
    ]
