# Generated by Django 3.0.6 on 2020-05-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_likes', to='forumapp.Like')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_answers', to='forumapp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_user', to='forumapp.NormalUser')),
            ],
        ),
    ]
