# Generated by Django 3.0.6 on 2020-05-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='verb',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_user', to='forumapp.NormalUser'),
        ),
    ]
