# Generated by Django 3.0.6 on 2020-05-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_likes', to='forumapp.Like'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_answers', to='forumapp.Question'),
        ),
    ]
