# Generated by Django 2.2.1 on 2020-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_auto_20200405_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
