# Generated by Django 3.0.6 on 2020-05-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_auto_20200512_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notify_answers', to='forumapp.Question'),
            preserve_default=False,
        ),
    ]
