# Generated by Django 2.2.1 on 2020-04-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0004_auto_20200406_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='normal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forumapp.NormalUser', verbose_name='select the field'),
        ),
    ]
