# Generated by Django 3.0.6 on 2020-05-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0005_auto_20200512_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
