# Generated by Django 2.2.1 on 2020-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0008_auto_20200410_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default=1, upload_to='question'),
            preserve_default=False,
        ),
    ]
