# Generated by Django 2.2.1 on 2020-04-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0009_auto_20200410_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='question'),
        ),
    ]
