# Generated by Django 2.2.1 on 2020-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0010_auto_20200410_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
