# Generated by Django 2.2.1 on 2020-04-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0011_auto_20200410_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forumapp.Answer'),
        ),
    ]
