# Generated by Django 2.2.1 on 2020-04-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0012_answer_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forumapp.Answer'),
        ),
    ]
