# Generated by Django 2.2.1 on 2020-04-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0016_auto_20200426_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='likes',
            new_name='like_question',
        ),
    ]
