# Generated by Django 2.2.1 on 2020-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0020_auto_20200427_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
